development:
  cloud_name: "videhost-herokuapp-com"
  api_key: "878717484735146"
  api_secret: "co3s3xyNY1VZ7CvdarZGehz5EXo"

production:
  cloud_name: "videhost-herokuapp-com"
  api_key: "878717484735146"
  api_secret: "co3s3xyNY1VZ7CvdarZGehz5EXo"
