# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: dkdottk
  password: 123321Danil

development:
  <<: *postgresql
  database: vhost_development

test:
  <<: *postgresql
  database: vhost_test

production:
  <<: *postgresql
  database: vhost_production
